name: sprouts_flutter
description: "Sprouts - Digital AR Pet Companions"
publish_to: 'none'

version: 1.0.5+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^12.1.3
  
  # UI & Basic Components
  flutter_staggered_grid_view: ^0.7.0
  
  # UI Enhancements & Animations
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  
  # Network & Storage
  dio: ^5.3.2
  shared_preferences: ^2.2.2
  path_provider: ^2.0.15
  
  # Media & Recording
  camera: ^0.10.5+5
  video_player: ^2.8.1
  image_picker: ^1.0.4
  permission_handler: ^10.4.5
  
  # 3D Model Rendering
  model_viewer_plus: ^1.7.2
  
  # HTTP & API
  http: ^1.1.0
  json_annotation: ^4.8.1
  
  # UI Helpers
  flutter_colorpicker: ^1.0.3
  image: ^4.1.3
  
  # Authentication
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  crypto: ^3.0.3
  uni_links: ^0.5.1
  
  # Icons
  cupertino_icons: ^1.0.8

  # Home Screen Widgets
  home_widget: ^0.6.0
  web3auth_flutter: ^6.3.0
  aptos: ^0.0.6
  hex: ^0.2.0
  pointycastle: ^3.7.3

dependency_overrides:
  path_provider_foundation: 2.3.2
  shared_preferences_foundation: 2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/animals/
    - assets/images/backgrounds/
    - assets/images/icons/
    - assets/models/
    - assets/icons/
    - assets/sprouts/
    
  # Fonts
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
          
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir.ttc
        - asset: assets/fonts/Avenir-Black.ttf
          weight: 900
          
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
